### ISSUE TITLE
Move to python 3.6

### ISSUE THREAD

**Issue by jjenthought** [force-h2020/force-bdss#197]
There's some useful features in 3.6 that aren't in 3.5 and the upgrade should be straigtforward as enthought is mostly building things for 3.6 at the moment.
One downside is that we have to do this for all the associated repos in the force-h2020 group, or at least the 'active' ones. And by active I mean the ones that have more than 1 commit total!

**Comment by jjenthought** [comment]
"Should be straightforward"...
There are some issues relating to serialization in traits 5.0.0-1, so it may be better to do the upgrade but keeping traits at 4.6.0-1. In the meantime we can investigate the cause of this within traits and upgrade when it's resolved.
Dict passed to `json.dump` - 3.6/5.0.0-1
`{'version': '1', 'workflow': {'mco': None, 'execution_layers': [], 'notification_listeners': []}}
<_io.TextIOWrapper name='/Users/mevans/src/force/force-bdss-plugin-enthought-example/enthought_example/random_pes_data_source/tests/workflow.json' mode='w' encoding='UTF-8'>
This is the example UI hook. The save is about to begin.
{'version': '1', 'workflow': {'mco': {'id': 'force.bdss.enthought.plugin.example.v0.factory.example_mco', 'model_data': {'parameters': [{'id': 'force.bdss.enthought.plugin.example.v0.factory.example_mco.parameter.ranged', 'model_data': {'initial_value': 0.0, 'lower_bound': 0.0, 'upper_bound': 5.0, 'name': 'x', 'type': 'f', '__instance_traits__': {'initial_value': <traits.traits.CTrait object at 0x1340742e8>, 'lower_bound': <traits.traits.CTrait object at 0x13404f240>, 'upper_bound': <traits.traits.CTrait object at 0x1260c2a20>, 'name': <traits.traits.CTrait object at 0x1260cb828>, 'type': <traits.traits.CTrait object at 0x1337c24e0>}}}], 'kpis': [{'name': 'y', 'objective': 'MINIMISE', '__instance_traits__': {'objective': <traits.traits.CTrait object at 0x142c322e8>, 'name': <traits.traits.CTrait object at 0x142c32c18>}}], '__instance_traits__': {'parameters': <traits.traits.CTrait object at 0x142c9e6d8>, 'parameters_items': <traits.traits.CTrait object at 0x142c32eb8>, 'kpis': <traits.traits.CTrait object at 0x133b71b70>, 'kpis_items': <traits.traits.CTrait object at 0x133b71cc0>}}}, 'execution_layers': [[{'id': 'force.bdss.enthought.plugin.example.v0.factory.example_data_source',
'model_data': {'power': 1.0, 'cuba_type_in': 'f', 'cuba_type_out': 'f', 'input_slot_info': [{'source': 'Environment', 'name': 'x', '__instance_traits__': {'name': <traits.traits.CTrait object at 0x1340a2d68>}}], 'output_slot_info': [{'name': 'y', '__instance_traits__': {'name': <traits.traits.CTrait object at 0x134016e10>}}], '__instance_traits__': {'trait_added': <traits.traits.CTrait object at 0x1340bd198>, 'cuba_type_in': <traits.traits.CTrait object at 0x1340bd978>, 'cuba_type_out': <traits.traits.CTrait object at 0x134117588>, 'power': <traits.traits.CTrait object at 0x142c24828>, 'changes_slots': <traits.traits.CTrait object at 0x1340e9e10>, 'input_slot_info': <traits.traits.CTrait object at 0x142c47048>, 'input_slot_info_items': <traits.traits.CTrait object at 0x142c47630>, 'output_slot_info': <traits.traits.CTrait object at 0x142c478d0>, 'output_slot_info_items': <traits.traits.CTrait object at 0x142c47a20>}}}]], 'notification_listeners': []}}`
Dict passed to `json.dump` - 3.5/4.6.0-1
`{'workflow': {'mco': {'model_data': {'kpis': [{'objective': 'MINIMISE', 'name': 'impurity_conc'}, {'objective': 'MINIMISE', 'name': 'mat_cost'}, {'objective': 'MINIMISE', 'name': 'prod_cost'}], 'evaluation_mode': 'Internal', 'num_points': 7, 'parameters': [{'model_data': {'upper_bound': 1.0, 'lower_bound': 0.0, 'name': 'volume_a_tilde', 'initial_value': 0.5, 'type': 'VOLUME'}, 'id': 'force.bdss.itwm.plugin.example.v0.factory.itwm_mco.parameter.ranged'}, {'model_data': {'upper_bound': 0.1, 'lower_bound': 0.001, 'name': 'conc_e', 'initial_value': 0.101, 'type': 'CONCENTRATION'}, 'id': 'force.bdss.itwm.plugin.example.v0.factory.itwm_mco.parameter.ranged'}, {'model_data': {'upper_bound': 400.0, 'lower_bound': 270.0, 'name': 'temperature', 'initial_value': 335.0, 'type': 'TEMPERATURE'}, 'id': 'force.bdss.itwm.plugin.example.v0.factory.itwm_mco.parameter.ranged'}` etc.

**Comment by ml-evs** [comment]
Hopefully PR #198 fixes all of the above, and should be bw-compatible with 3.5/4.6.0. Dunder keys are recursively removed in the `__getstate__()` call for most base classes, circumventing this serialisation issue. I've made a few PRs for the other repositories too (e.g. https://github.com/force-h2020/force-bdss-plugin-itwm-example/pull/36).

**Comment by jjenthought** [comment]
Closed by #198
