### ISSUE TITLE
Factory plugin trait seems to be excessive

### ISSUE THREAD

**Issue by corranwebster** [force-h2020/force-bdss#209]
As best I can tell, the `factory.plugin` trait is only used for extracting the `id` of the plugin (mainly for error reporting purposes, which is good) but carrying around the entire Envisage `plugin` seems excessive when perhaps just remembering `plugin_id` or other information may be enough.

**Comment by corranwebster** [comment]
On a bit further digging, there is at least one place where the `Plugin` API is actually used in the `ExampleMCO` which it is used to get the application to in turn find the location of the workflow file on disk (ie. `factory.plugin.application.workflow_filepath`) which is bad on many levels.  If MCOs need to know the location fo the workflow on disk, then there should be a better way to provide it.

**Comment by flongford** [comment]
At the moment the `Plugin` API is also used in every example use case `BaseMCO` subclass to obtain the `Workflow` object through `factory.plugin.application.workflow`.

It would seem to make more sense for the `BaseMCO.run` method to require a `Workflow` argument to be passed in alongside a `BaseMCOModel` instance instead.

**Comment by flongford** [comment]
Actually, the `BaseMCOModel ` argument passed into `BaseMCO.run` method in the `force-bdss` runner is an attribute of the `Workflow`....

So actually everything required for an MCO optimisation to be performed by a `BaseMCO` class is contained in the `Workflow` object.
