### ISSUE TITLE
New point notification with non-standard data

### ISSUE THREAD

**Issue by Corwinpro** [force-h2020/force-bdss#239]
Currently, the MCO `run` method notifies that a new (optimal) point has been found via the `BaseMCO().notify_new_point` method. The `notify_new_point` method accepts two generic arguments (`optimal_point, optimal_kpis`), and a `weights` argument. The last one seems to be relevant to a very specific optimization algorithm (`WeightedOptimizer`) only, and ambiguous to others.

It feels that a less specific attribute can be passed to `notify_new_point`, for instance, as a simple `**kwargs` instead of `weights`. That would allow us to communicate a broader range of optimization data, and would suit any optimization algorithm.

I have not checked how this problem may affect the UI part of the program.

**Comment by flongford** [comment]
This is similar to #200
