### ISSUE TITLE
Workflow has a misleading `mco` attribute

### ISSUE THREAD

**Issue by Corwinpro** [force-h2020/force-bdss#246]
Class `Workflow` has a `mco = Instance(BaseMCOModel, allow_none=True)` attribute.

It seems to be very confusing that it is called `mco` instead of `mco_model`, especially considering that there is a separate `BaseMCO` entity.

I can suggest changing the attribute name to `mco_model` - this better reflects the actual object type corresponding to this `Workflow` attribute.

**Comment by flongford** [comment]
This seems like a very sensible idea to me

**Comment by Corwinpro** [comment]
FIxed in #257
