### ISSUE TITLE
Upper bound attribute for KPIs

### ISSUE THREAD

**Issue by Corwinpro** [force-h2020/force-bdss#293]
`KPISpecification` class should implement a `bound` attribute (upper bound for minimization, and lower bound for maximization). This attribute is required by the gradient-free multiobjective optimization algorithms. It also seems quite sensible to implement it in general, as if we have two contradicting objectives, it might be possible that one of those will go to infinity over the course of optimization while the second one is optimized.

**Comment by flongford** [comment]
Closed by #353
