### ISSUE TITLE
EvaluateOperation should verify Workflow first

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss#317]
Currently, the `EvaluateOperation.run` method does not call the `Workflow.verify` method before evaluating the KPIs for a given set of parameter values. This is problematic, since it's possible that a single evaluation point could take a long time to execute, which would be wasted if it breaks at any point.

The `OptimiseOperation.run` method does, however, verify the `Workflow` object before performing its optimization task. Therefore we could also share the same code (possibly through a `BaseOperation` class #310) in order to resolve this.

**Comment by sparsonslab** [comment]
I've tried porting `self.workflow_file.verify()` from the optimizer_operation, and the log.error code that follows it, into the base_operation in two ways:
1) putting it directly into `BaseOperation.run()` and then calling super in the run() of the optimizer and evaluator operations.
2) making a `BaseOperation.verify_workflow()` method that is called by run() of the optimizer and evaluator operations.
In both cases I get a heap of unit test errors, including ones in non-operation test (e.g. `test_cli_execution.py` that I can't untangle.
I might need some help on this one.

**Comment by flongford** [comment]
> I've tried porting `self.workflow_file.verify()` from the optimizer_operation, and the log.error code that follows it, into the base_operation in two ways:
> 
> 1. putting it directly into `BaseOperation.run()` and then calling super in the run() of the optimizer and evaluator operations.
> 2. making a `BaseOperation.verify_workflow()` method that is called by run() of the optimizer and evaluator operations.

Just as a side comment, I would opt for option 2 here as our final approach, since it feels cleaner.

> In both cases I get a heap of unit test errors, including ones in non-operation test (e.g. `test_cli_execution.py`) that I can't untangle.
> I might need some help on this one.

Yuck, that sounds messy - I think I have an idea of what's going on, so feel free to make the PR anyway in order to share the error messages. You can always put 'WPI:' at the start of the PR name to show that it is not ready to be merged yet.
