### ISSUE TITLE
Listener related methods on OptimizeOperation can be ported to BaseOperation

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss#319]
Since #316 we have a `BaseOperation` class  that contains `stop` and `pause` threading events.

However, at the moment, the `EvaluateOperation` class does not set up any `BaseNotificationListener` instances that could influence the `stop` and `pause` events. Therefore we should share the code from `OptimizeOperation` that handles these listener objects, by porting the relevant methods to `BaseOperation` and invoking them from `EvaluateOperation.run`

Overall, we should be left with a `BaseOperation` class containing:

- [ ] `BaseOperation.listeners` attribute
- [ ] `BaseOperation._*_event` methods
- [ ] `BaseOperation._*_listeners` methods

And an `EvaluateOperation.run` method that initialises and finalises the listeners / events before performing its main task

**Comment by sparsonslab** [comment]
Should I create a test_base_operation.py with the listener unit tests common to evaluate and optimize operations?

**Comment by flongford** [comment]
> Should I create a test_base_operation.py with the listener unit tests common to evaluate and optimize operations? Or should the listener unit tests for optimizer be reproduced for the evaluator?

Yes, creating a `test_base_operation.py` file containing these listener test sounds like a good idea, since it avoids duplication of code.
