### ISSUE TITLE
WeightedOptimizerEngine could inherit from ScipyOptimizerEngine

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss#321]
At the moment, we offer the `WeightedOptimizerEngine` class as a useful object to be used in any `BaseMCO.run` implementation. However, it is currently providing two key functionalities, which could be separated: an entry point to the `scipy.optimizers` package, and the ability to assign importance weights to KPIs.

It may be beneficial to create a new subclass of `BaseOptimizerEngine` that only exposes the `scipy.optimizer` routines, which `WeightedOptimizerEngine` would then inherit from. ~By doing so, we may also explore the SciPy 'ask and tell' interface, similar to our Nevergrad plugin classes.~

Note: as of writing (8/04/20) the SciPy library does not have an "ask and tell" API for its optimiser module.

Solving this issue will require the following:
- [x] A new class: `SciPyOptimizerEngine`, inheriting from `BaseOptimizerEngine`. This should fulfil the base class API only and act as an entry point for the `scipy.optimizer` library. Much of the current required functionality is probably contained in the `WeightedOptimizerEngine._weighted_optimize` method.

- [ ] Refactoring `WeightedOptimizerEngine` to inherit from `SciPyOptimizerEngine`. This could be done in a number of ways, but we should focus on keeping the weighted features independent from the optimization library being used. A `WeightedKPISearch` mixin class might therefore be appropriate, which could also be used with any other `BaseOptimizerEngine` subclass

**Comment by flongford** [comment]
We could handle KPI weights in a different way - maybe as attributes of the `KPISpecification` class?

**Comment by sparsonslab** [comment]
Things the user might want to do, that could be implemented as a generic MCO "Model" class (i.e. Traits view). 

* Sample (the objective function)
	* random
	* grid
* Optimize (find the minima/maxima of the objective function)
	* what optimizer I want to use. Each one should be associated with a implementation of the 	BaseOptimizerEngine class.
		* scipy (just gradient)
		* scikit (Bayesian, forest regression, etc)
		* nevergrad (many!)
	* what I want to do with the optimizer. These could be collected together as an interface that each OptimizerEngine has to 	implement. e.g. optimize_single_x0().
		* from single x0 (search for single minimum)
		* from random x0 (search for all minima)
		* Pareto front/set
			* A priori methods (can be applied using any optimizer)
				* scalarisation (i.e. like "weighted optimizer")
			* A posteriori methods (only implemented in some packages: e.g. nevergrad).
		* get all points on optimization search path (using ask/tell)
		* user steered (using ask/tell)

**Comment by flongford** [comment]
There are some good ideas here, it will be interesting to see how they can be implemented in both the existing `NevergradOptimizerEngine` and proposed `ScipyOptimizerEngine` classes. Some may be more adventurous than others (i.e Pareto front), so it would probably make sense to define a minimal API to begin with - I think the existing one (`BaseOptimizerEngine.optimize`) is probably sufficient for the `ScipyOptimizerEngine`.

Additionally, it's worth keeping in mind that If the BDSS requires every MCO to possess certain features that sit above the optimizer backend, then we should probably look to expand on the `BaseMCO` and `BaseMCOModel` classes instead.

**Comment by flongford** [comment]
_(Although a bit off topic, this might provide some useful context)_:

At the moment the `BaseOptimizerEngine` sits in the backend, we have no UI features for it. In fact, all of the UI feature must be implemented in the `BaseMCOModel` class, and propagated through a `BaseMCO.run` method .

Originally (https://github.com/force-h2020/force-bdss-plugin-itwm-example/pull/55/files) when developing the `BaseOptimizerEngine` class, we integrated it into the `BaseMCOModel` view features, so the user could swap between different engines in the UI. Although useful from a UX perspective, this became a very messy in the backend since it did not fit within the design of the BDSS plugin system. In fact the `BaseOptimizerEngine` started to take over the role of the `BaseMCO` class, but without any envisage support.

We eventually decided to reduce the exposure of the `BaseOptimizerEngine` to the user, and keep it as a useful utility tool for quickly integrating external libraries. The lesson learnt was that it becomes painful quickly if we start work too much outside the existing design framework of BDSS.

**Comment by sparsonslab** [comment]
> There are some good ideas here, it will be interesting to see how they can be implemented in both the existing `NevergradOptimizerEngine` and proposed `ScipyOptimizerEngine` classes. Some may be more adventurous than others (i.e Pareto front), so it would probably make sense to define a minimal API to begin with - I think the existing one (`BaseOptimizerEngine.optimize`) is probably sufficient for the `ScipyOptimizerEngine`.
> 
> Additionally, it's worth keeping in mind that If the BDSS requires every MCO to possess certain features that sit above the optimizer backend, then we should probably look to expand on the `BaseMCO` and `BaseMCOModel` classes instead.

Exactly. In what I am suggesting you would have a single `BaseMCOModel` and `BaseMCO` to run multiple engines (rather than the present, one-MCOModel and one-MCO for each engine). The former allows the user to select different optimisers and tasks. The latter then can create any one of the `BaseOptimizerEngine` objects, depending on what optimiser has been selected, and then call the task method on that object, depending on what task has been called. If the optimizer cannot implement that it would return and exception/message.

**Comment by sparsonslab** [comment]
> At the moment the `BaseOptimizerEngine` sits in the backend, we have no UI features for it. In fact, all of the UI feature must be implemented in the `BaseMCOModel` class, and propagated through a `BaseMCO.run` method, which feels inefficient.

Yes it is kind of inefficient, but makes sense for my idea. Thanks for the history. Its a bit like biblical exegisis (the bible being Traits!).

**Comment by flongford** [comment]
> > At the moment the `BaseOptimizerEngine` sits in the backend, we have no UI features for it. In fact, all of the UI feature must be implemented in the `BaseMCOModel` class, and propagated through a `BaseMCO.run` method, which feels inefficient.
> 
> Yes it is kind of inefficient, but makes sense for my idea. Thanks for the history. Its a bit like biblical exegisis (the bible being Traits!).

Yea and verily so

**Comment by flongford** [comment]
> Exactly. In what I am suggesting you would have a single `BaseMCOModel` and `BaseMCO` to run multiple engines (rather than the present, MCOModel + MCO for _each_ engine). The former allows the user to select different optimisers and tasks. The latter then can create any one of the `BaseOptimizerEngine` objects, depending on what optimiser has been selected, and then call the task method on that object, depending on what task has been called. If the optimizer cannot implement that it would return an exception/message.

I think it would be very useful to have this abstraction between MCO and engine. I would recommend looking at https://github.com/force-h2020/force-bdss-plugin-itwm-example/pull/55/files as _not quite_ a way to achieve this. It was nearly there, but we just had too much overlap between the `BaseMCOModel` and `BaseOptimizerEngine` (i.e - both had `kpi` and `parameter` attributes)

An alternative way may be to have the `BaseMCOFactory` able to support multiple `BaseOptimizerEngine` classes instead, and then include these in the envisage framework

**Comment by sparsonslab** [comment]
Yeah, I hadn't thought about the factorys. At the moment the factories, don't concern themselves with returning engine classes (there is no get_engine_class()), so we would only need a single factory to go with the single MCO+MCOModel.

**Comment by flongford** [comment]
> Yeah, I hadn't thought about the factorys. At the moment the factories, don't concern themselves with returning engine classes (there is no get_engine_class()), so we would only need a single factory to go with the single MCO+MCOModel.

Exactly, if we want to be able to swap between the engines then I guess we'll need to come up with a registry of those that are currently supported (maybe in a similar way to the `BaseMCOParameter` classes).

**Comment by sparsonslab** [comment]
Depends if the engines come together with the MCO+MCOModel in a one-time plugin, or we want to be able to add engines as separate plugins. The former is easier, but of course the later is what we should be doing (like you say). Like everything in life, its a choice between "the proper way" and "the easy way"..... and well we are proper aren't we?

At the moment there is no registry (I guess) because every MCO/MCOModel assumes it comes with a matching engine.

**Comment by sparsonslab** [comment]
> An alternative way may be to have the `BaseMCOFactory` able to support multiple `BaseOptimizerEngine` classes instead, and then include these in the envisage framework.
> 
> We could then look at changing the WfManager UI to make it easier to switch between these objects in an MCO run (have them all visible in a single task at the same time)

This of course would be the *most* proper way, but is definitely *not* the easy way - it require the biggest change to the current architecture. Maybe one for BDSS 2.0.

**Comment by sparsonslab** [comment]
> The lesson learnt was that it becomes painful quickly if we start work too much outside the existing design framework of BDSS.
.. exactly!

**Comment by sparsonslab** [comment]
> At the moment, we offer the `WeightedOptimizerEngine` class as a useful object to be used in any `BaseMCO.run` implementation. However, it is currently providing two key functionalities, which could be separated: an entry point to the `scipy.optimizers` package, and the ability to assign importance weights to KPIs.
> 
> It may be beneficial to create a new subclass of `BaseOptimizerEngine` that only exposes the `scipy.optimizer` routines, which `WeightedOptimizerEngine` would then inherit from. ~By doing so, we may also explore the SciPy 'ask and tell' interface, similar to our Nevergrad plugin classes.~
> 
> Note: as of writing (8/04/20) the SciPy library does not have an "ask and tell" API for its optimiser module.
> 
> Solving this issue will require the following:
> 
> * [ ]  A new class: `SciPyOptimizerEngine`, inheriting from `BaseOptimizerEngine`. This should fulfil the base class API only and act as an entry point for the `scipy.optimizer` library. Much of the current required functionality is probably contained in the `WeightedOptimizerEngine._weighted_optimize` method.
> * [ ]  Refactoring `WeightedOptimizerEngine` to inherit from `SciPyOptimizerEngine`. This could be done in a number of ways, but we should focus on keeping the weighted features independent from the optimization library being used. A `WeightedKPISearch` mixin class might therefore be appropriate, which could also be used with any other `BaseOptimizerEngine` subclass

To do it this way, could you clarify a little?:
- So the `SciPyOptimizerEngine.optimize()`  should only return a single point and the `WeightedOptimizerEngine` should override this and be essentially what it is now?
- when you mean separate the weighting do you mean both the scaling and the weight-space-sampling or just one of those?

**Comment by flongford** [comment]
> To do it this way, could you clarify a little?:
> 
> * So the `SciPyOptimizerEngine.optimize()`  should only return a single point and the `WeightedOptimizerEngine.optimize()` should override this and be essentially what it is now?

Yes, a good starting point is to just make a new class: `SciPyOptimizerEngine`, with an `optimize` that performs the equivalent of `NevergradOptimizerEngine.optimize`, but uses the `scipy.optimize` library as a backend. We can then think how `WeightedOptimizerEngine.optimize` should inherit from / overwrite this afterwards to return the same as it does now.

> * when you mean separate the weighting do you mean both the scaling and the weight-space-sampling or just one of those?

In this case all the KPI weight-space-sampling features that sit on top of the calls to the `scipy.optimize.minimize` function. I expect this part to be a bit more complex, so best dealt with in a separate PR after creating the `SciPyOptimizerEngine`.
