### ISSUE TITLE
reathedocs fails at building the docs

### ISSUE THREAD

**Issue by dpinte** [force-h2020/force-bdss#350]
From https://readthedocs.org/projects/force-bdss/builds/11021492/ 

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/doc_requirements.txt'
```

**Comment by flongford** [comment]
The ReadTheDocs build is now passing, but not generating the autoapi - I think this can be dealt with in the readthedocs configuration file
