### ISSUE TITLE
Personalize __getstate__ so that we create the appropriate dictionary for objects created by factory.

### ISSUE THREAD

**Issue by stefanoborini** [force-h2020/force-bdss#67]
Right now the writer is clumsy, the reason is that we use the default ``__getstate__``. We can reimplement it so to return the id of the factory and the model content instead.

**Comment by jjenthought** [comment]
I think this may have been closed by previous work, but #198 has also added custom `__getstate__` methods for the base classes, which can be modified to give more useful dictionaries if things change further.
